### ISSUE TITLE
Change license

### ISSUE THREAD

**Issue by tssge** [net9-oy/whmcs-ficoraepp#18]
As the Metaregistrar EPP client used by this plugin is GPLv2 licensed, this plugin cannot be LGPLv2 licensed as it currently is.

The license needs to be changed to GPLv2 and all contributors need to agree.

Please acknowledge @korhox and @olkitu

**Comment by olkitu** [comment]
Acknowledge

**Comment by korhox** [comment]
Acknowledged.
