### ISSUE TITLE
Compatibility with WHMCS 8.X.X?

### ISSUE THREAD

**Issue by GVeidenberg** [net9-oy/whmcs-ficoraepp#20]
Can`t get to work with WHMCS 8.0.2.
Anybody else has problems? Or just me?
Thank You

**Comment by chinmay241** [comment]
Works fine here :)

**Comment by tssge** [comment]
Sorry for late response. We have done testing with WHMCS 8.0.x and confirmed it works fine and updated the marketplace listing accordingly.

If there is some issue with 8.0.x you are facing, please open a specific issue.
